[project]
name = "cardstudio"
version = "0.0.2"

description = "Full card customization for Ballsdex."
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "hiboman", email = "hiboman@proton.me" },
]
readme = "README.md"

# dependencies = [
#     "ballsdex>=3.0.0",
# ]

[project.urls]
Repository = "https://github.com/hiboman/BallsDex-CardStudio-Pack"
Documentation = "https://github.com/hiboman/BallsDex-CardStudio-Pack#readme"
Issues = "https://github.com/hiboman/BallsDex-CardStudio-Pack/issues"
